### ISSUE TITLE
Error add new scanner (Nessus, Acunetix)

### ISSUE THREAD

**Issue by sonpd2** [Mixeway/MixewayHub#27]
When I add a new scanner, the response has error: {"status":"I/O error on GET request for \"https://private_ip:8834/editor/scan/templates\": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","requestId":null}
Please show me how to fix it

**Comment by sonpd2** [comment]
I found the way

**Comment by nibiwodong** [comment]
how to fix this?

**Comment by nibiwodong** [comment]
I see. Just use HTTP, do not use HTTPS

**Comment by siewer** [comment]
@nibiwodong mode info required what to fix.
I assume You are trying to integrate with Nesus (please note that working integration in scope of scan creation and configuration, scan running and vulnerability loading works only with Nessus v6 and bellow,  > v7 drop support for rest API)

If You have TLS on any scanner You want to use with Mixeway there is a requirement for Mixeway to trust it. If You are using corporate CA or self-signed certificate on nessus or any scanner You have to import it into MixewayHub's trust store by doing:

Mixeway TrustStore is in <root>/pki/trust.jks (password in environment file)

to add scanner certificate to this store use:
`keytool -import -alias scanner-file <scanner.crt>-storetype JKS -keystore pki/trust.jks`
