### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by madchap** [Mixeway/MixewayHub#7]
Hi,

A demo site would be great at some point to painlessly give a shot to the tool! (even if limited in its actions)

Cheers :)

**Comment by siewer** [comment]
I can't think of any useful scenarios to host a demo site unfortunately.

Mixeway has Vulnerability Management System functionalities but it is not the main function.
The main objective of Mixeway is to orchestrate tools used within the organization (in the most scenarios somewhere in private networks) so it would be extremely hard to integrate Mixeway hosted on the internet with tools located in the organization's network.

The hosting demo site in this scenario would just allow seeing a prepopulated dashboard with some random projects and vulns without the possibility to add a Vulnerability scanner or run a scan.

**Comment by madchap** [comment]
This is fair enough. Thanks for the answer.
