### ISSUE TITLE
Can't add scanner

### ISSUE THREAD

**Issue by 6mile** [Mixeway/MixewayHub#9]
Hi, I'm trying to add an OpenVAS 8.0 scanner to a Mixeway server we've spun up and its not working.  Can you point me in the right direction for how to add a scanner because your documentation page doesn't actually show the values you used to setup a scanner.  For example, does the API URL field accept IP4 addresses?  Does it expect FQDN?  Do I have to add http:// or https://?   No matter what I put in the API URL field I don't get any traffic when it tests.  
This is the error we get from the docker container:  
MixerBackend     | 2020-03-09 06:01:25.586 ERROR 1 --- [nio-8443-exec-9] i.m.r.a.service.AdminScannerRestService  : Error during scanner testing 

Network is wide open between the Mixeway server and my OpenVAS box.  I can curl the OpenVAS box from the CLI on the mixeway server successfully.  However, when I add the scanner in the Mixeway UI I never see any traffic.  If I click the "test" button I don't see traffic, so that makes me think that the API URL field is not right.  
![mixeway-scanner](https://user-images.githubusercontent.com/7798480/76189642-efd1ba00-6226-11ea-86fe-afe14f2216d4.png)

**Comment by siewer** [comment]
itegration versions are listed here:
https://mixeway.github.io/requirements/
Mixeway v1.0.0, was tested using OpenVAS 9 - I am not quite sure if 8.0 XML API is the same.

However first things first:
1. Please set scanner type to "OpenVAS Socket". OpenVAS scanner type is for REST API we are developing and we will release OpenVAS REST API client shortly. I will try to create PR for both documentation and frontend tooptips so it will be clear
2. API URL is URL openvas manager is listening on with protocol for example: https://127.0.0.1:9390


I have just tested it using openvas 9 docker and it works ok - https://github.com/mikesplain/openvas-docker
